version: '3'
services:
  db:
    image: postgres:12
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myCAvb7bC7ySoplLnpeL3m8pW7WyyLun
      POSTGRES_DB: nest_jwt
